### PR TITLE
Bugfix/nexteuropa 11426

### PR DESCRIPTION
**Pull request by Fefaine**

### CODE REVIEW

**Comment by tatarbj** [comment]
@Fefaine are you sure from ldap (or make it generic: everywhere) the original data is stored in ISO-8859-1. Maybe to use https://api.drupal.org/api/drupal/includes%21unicode.inc/function/drupal_convert_to_utf8/7.x is a bit safer for long term.

**Comment by netlooker** [comment]
:+1:

**Comment by Fefaine** [comment]
:+1:

**Comment by netlooker** [comment]
@tatarbj we decided to solve login issue in first place. After that 
we are going to address character coding issue in follow up ticket NEXTEUROPA-11605.

**Pull request merged**
