### PR TITLE
NEPT-1377: Remove rule for which we have no errors.

### PR DESCRIPTION
**Pull request by Fefaine**
### Description

Remove PHPCS rule exception for which we have no errors.

### Change log

- Removed: Exception rule in phpcs-qa file

### Commands

```sh
no command
```

### CODE REVIEW

**Comment by dxvargas** [comment]
👍

**Comment by drupol** [comment]
👍

**Comment by drupol** [comment]
We need a rebase.

**Comment by drupol** [comment]
👍

**Comment by drupol** [comment]
Ready to be merged.

**Pull request merged**
