### PR TITLE
Feature/newsroom multilingual

### PR DESCRIPTION
**Pull request by planctus**
Related to: https://webgate.ec.europa.eu/CITnet/jira/browse/MULTISITE-7232
Creating the pull request for merging the NEWSROOM_multilingual branch in the "cnect" fork of the platform-dev repo in the master branch of the platform-dev repo. 
The feature branch has been kept in sync with the develop branch of the platform-dev repo but the pull request is against master because the feature should be included in the 2.1.* version of the platform. 
I see that apparently git is showing many modified files coming from other commits in other branches even if we tried not to merge directly branches into our custom one.
The relevant code is in the nexteuropa_newsroom feature which carries also a custom module named newsroom.
I had a simpletest failing but the failure was due to the parent classes setup (feeds) function which was throwing errors in my environment.
By the way, i'm switching project tomorrow so please communicate with Nikolay Lobachev about issues on this pull request.

### CODE REVIEW

**Comment by degliwe** [comment]
If you want this feature to be available during the platform 2.1 lifecycle. I would then recommend to rebase your branch on the master branch (instead of develop) and re-create a pull request, we will then be able to merge into master and deploy as soon as you want, also we will be able to merge this easily to develop (which is already 2.2)

https://git-scm.com/book/en/v2/Git-Branching-Rebasing 
    `$ git rebase --onto master develop`
If you integrated the changes from the develop to your branch on a regular basis it may be an issue.

You'll then have to force push your feature branch against your origin:
    `$ git push –force origin feature/NEWSROOM-Multilingual`

@pfrenssen feel free to complete my comment.

**Comment by pfrenssen** [comment]
Won't this affect existing websites? The 2.1 release is already out. It was my understanding that we can only deploy urgent bugfixes and a very limited range of features as hotfixes. Wouldn't it be better to wait until the 2.2 release? Which websites are using this?

This branch is not clean, so rebasing this will need a lot of manual work. I've seen that this contains changes to files outside the scope of the issue, and it reintroduces problematic commits that were already cleaned up in the past. For example an accidental commit of a database dump (commit ba9edfcb4d57f9c3ee) reappears in this branch. This (and all other unrelated changes) will need to be removed from this pull request before we can accept it.

The command to rebase this would be the following:

```
$ git rebase --onto master develop feature/NEWSROOM-Multilingual
```

The problem is that this contains a lot of commits, and since this was started back in June there have been *many* changes to the Newsroom feature. I have attempted to rebase it but had to give up after two hours of endless merge conflicts. I am not familiar with the code base and lost track of the countless changes.

**Comment by pfrenssen** [comment]
OK so this is a new feature that doesn't yet exist on the platform. So this is allowed as a hotfix for 2.1 since it won't affect existing websites.

I'm afraid that untangling this would take many hours of work, so it might be better to simply do a code drop in a single commit.

**Comment by degliwe** [comment]
So in order to get back on track.
The recommendations are:
- sync your repo with platform-dev https://help.github.com/articles/syncing-a-fork/
- create a new feature branch branch from master
- drop your newsroom code here.
- create a pull request to platform-dev/master

I close this pull request.
You can also delete this branch. 

@LOBsTerr @planctus @pfrenssen

**Pull request closed without merging**
