### PR TITLE
NEPT-771: Added patch to prevent remaining inside media span when add…

### PR DESCRIPTION
**Pull request by imanoleguskiza**
…ing new lines (#1285)

### CODE REVIEW

**Comment by Fefaine** [comment]
:+1

**Comment by Fefaine** [comment]
👍

**Comment by gillesdeudon** [comment]
:+1:

**Comment by Fefaine** [comment]
Removing my +1 since jenkins failed.. :(

**Comment by Fefaine** [comment]
Replaced with https://github.com/ec-europa/platform-dev/pull/1312

**Pull request closed without merging**
