### PR TITLE
NEXTEUROPA-12156: Add bean-entity_render_contextual_links_fix-1954950…

### PR DESCRIPTION
**Pull request by voidtek**
NEXTEUROPA-12156: Add bean-entity_render_contextual_links_fix-1954950-7-D7.patch
https://webgate.ec.europa.eu/CITnet/jira/browse/NEXTEUROPA-12156

### CODE REVIEW

**Comment by drupol** [comment]
Just for the record, link to the drupal.org issue: https://www.drupal.org/node/1954950

**Comment by drupol** [comment]
This has been reopened because we were unable to display the Contextual Links after applying the patch.
We tried with different themes, the expected result didn't succeeded.

**Comment by drupol** [comment]
:+1:

**Comment by drupol** [comment]
Dear @cyberwolf,

The official patch for bean enable the contextual links through the $title_prefix variable and also add the display of the title in the template (to be consistent).
To avoid unexpected behaviors on our subsites, we've overridden the default template in our theme to only display the contextual links and not the title.

**Comment by cyberwolf** [comment]
Ok thanks for the clarification @dxvargas.
I tested it and it seems to work well.

👍

**Comment by drupol** [comment]
You're welcome @Fefaine.

**Comment by verbruggenalex** [comment]
Hey @drupol , if I'm not mistaken only the $title_suffix contains the actual contextual links. I'm not fully sure what $title_prefix and $title_suffix can output. If users did not make use of titles on the beans before I think it's safer to just output what you need:
```
<div class="<?php print $classes; ?> clearfix"<?php print $attributes; ?>>
  <?php if (isset($title_suffix['contextual_links'])): ?>
  <?php print render($title_suffix['contextual_links']); ?>
  <?php endif; ?>
  <div class="content"<?php print $content_attributes; ?>>
    <?php print render($content); ?>
  </div>
</div>
```

This is also the way that display suite handled it before: https://www.drupal.org/node/1032868

**Comment by Fefaine** [comment]
:+1:

**Comment by imanoleguskiza** [comment]
:+1:

**Pull request merged**
