### PR TITLE
NEXTEUROPA-11189: Updating media_youtube module '2.0-rc5' to '3.0'

### PR DESCRIPTION
**Pull request by voidtek**
https://webgate.ec.europa.eu/CITnet/jira/browse/NEXTEUROPA-11189

### CODE REVIEW

**Comment by voidtek** [comment]
:+1:

**Comment by voidtek** [comment]
:+1:

**Comment by yhuard** [comment]
:-1:

**Comment by yhuard** [comment]
:+1:

**Comment by voidtek** [comment]
:+1:

**Pull request merged**
