### PR TITLE
fix(contributing): Removing permission 'use media wysiwyg'

### PR DESCRIPTION
**Pull request by netlooker**
- removing 'use media wysiwyg' permission from the multisite_wysiwyg feature
- fixing failing test scenario (new step implementation)

### CODE REVIEW

**Comment by imanoleguskiza** [comment]
👍

**Comment by Fefaine** [comment]
I agree with @voidtek 
We should provide a hook_install that will grant this permission to administrator, editor and contributor
On a fresh install a contributor should be able to use the wysiwyg, that a basic editorial feature !

**Comment by dxvargas** [comment]
👍

**Comment by imanoleguskiza** [comment]
👍

**Pull request merged**
