### PR TITLE
NEPT-255: Fix: Missing user_default.png and empty_gallery.png files

### PR DESCRIPTION
**Pull request by drupol**
Fix: Missing user_default.png and empty_gallery.png files

This is to prevent warnings during install.

### CODE REVIEW

**Comment by dxvargas** [comment]
👍

**Comment by Fefaine** [comment]
Closing this PR as it should be in 2.3.0

**Comment by drupol** [comment]
Rebased against 2.3.

**Comment by drupol** [comment]
forwared to #992

**Pull request closed without merging**
