### PR TITLE
NEPT-2137: Restore dependency declaration to ex-tidy

### PR DESCRIPTION
**Pull request by AlbaParrilla**
### Description

ext-tidy dependency declaration was removed from the composer.json file by mistake and it has to be restored

### Change log

- Changed: composer.json and composer.lock

### Commands

No commands

### CODE REVIEW

**Review by aritomelo — APPROVED** [review]
Ready to go.

**Review by AlbaParrilla — COMMENTED** [review]
The comment about Poetry that should be added, as it is in acceptance criteria, could not be added as json files cannot have comments.

**Review by ku-enza — APPROVED** [review]
Ok with this

**Review by Fefaine — APPROVED** [review]
ok for me

**Pull request merged**
