### PR TITLE
Bugfix/nexteuropa 11868 test

### PR DESCRIPTION
**Pull request by voidtek**
https://webgate.ec.europa.eu/CITnet/jira/browse/NEXTEUROPA-11868

### CODE REVIEW

**Comment by jfhovinne** [comment]
:+1:

**Comment by jfhovinne** [comment]
Did not test the test.

**Comment by voidtek** [comment]
The test pass with success in CPHP.

**Comment by netlooker** [comment]
I've checked code and I've run feature against fresh platform install. All steps passed correctly.

**Comment by netlooker** [comment]
:+1:

**Pull request merged**
