### PR TITLE
NEPT-153: Rearrange behat tests parallelization -  fix(improvement)

### PR DESCRIPTION
**Pull request by voidtek**
https://webgate.ec.europa.eu/CITnet/jira/browse/NEPT-153

Into the branch "master"

### CODE REVIEW

**Comment by drupol** [comment]
:+1:

**Comment by Fefaine** [comment]
:+1:

**Comment by ademarco** [comment]
We will actually try a merge in 2.4 before merging this in, it should work but it's better to be extra sure.

**Comment by ademarco** [comment]
Closing as invalid, check NEPT-153 for a full overview of this issue.

**Pull request closed without merging**
