### PR TITLE
Feature/nexteuropa 12501 Provide documentation on poetry

### PR DESCRIPTION
**Pull request by Fefaine**

### CODE REVIEW

**Comment by voidtek** [comment]
:+1:

**Comment by jazio** [comment]
Very good initiative to separate the two users.


Webmaster / Site builder:
=================================

In the section: Enabling the feature on your platform instance:

I may suggest

Poetry is not a feature you can enable using feature sets.

to be redited:

Poetry feature can not be enable using feature sets.

Reading it in high speed could mean the opposite.


2 rows down
"Create a support ticket in Jira's MULTISITE project explaining the details and deadlines for your request:"

The link to Jira should be better: https://webgate.ec.europa.eu/CITnet/jira/secure/RapidBoard.jspa

"Create a support ticket in Jira's MULTISITE project explaining the details and deadlines for your request:"
could be
"Create a support ticket in Jira's MULTISITE project (the blue button labeled `Create`). Explain the details and deadlines for your request:"

It is proved helpful to have the deadline crafted in the jira ticket title.


The link to management translator is incorrect, I suggest breaking it into 2 steps:

It is Configuration > Regional and language > Translations Management Translator
admin/config/regional/tmgmt_translator_en

then click Edit link

(or directly admin/config/regional/tmgmt_translator/manage/poetry_en)


Maintenance staff (FPFIS staff)
======================================

Playground
---------------

Tested succesfully

Job has been successfully submitted for translation. Project ID is: MAIN_143_POETRY_WEB/2016/40005/1/29/TRA
  
  
Production
-----------------------

"The values of [CALLBACK_USERNAME] should match NE-projectname where projectname is the project's code. Example: NE-ERASMUSPLUS
[CALLBACK_PASSWORD] is the same as the callback_username. These fields are limited to 15 characters."

It means the production credentials are completely predictible? This could be helpful as I no longer need to ask for them.

**Comment by Fefaine** [comment]
Thank Ovi
To answer your question "It means the production credentials are completely predictible? This could be helpful as I no longer need to ask for them." yes: the callback password is predictable.
The poetry password is not.
I am waiting for DG COMM feed back on how the client should request the service to DGCOMM and i expect THEY will send you the password and you won't have to request it !

**Comment by Fefaine** [comment]
:+1:

**Comment by netlooker** [comment]
👍

**Pull request merged**
