### PR TITLE
NEPT-161: Upgrade menu_token to beta7 and remove patch.

### PR DESCRIPTION
**Pull request by drupol**
fix: update to latest stable release, released in March 2016.

### CODE REVIEW

**Comment by cyberwolf** [comment]
👍

**Comment by verbruggenalex** [comment]
:-1: 
QA finished, we can not update the module until this issue is resolved:
https://www.drupal.org/node/2826475

entity_get_info does not always return path, for nodes it should still rely on entity_uri() to get the path

**Comment by voidtek** [comment]
:+1:

**Comment by drupol** [comment]
https://www.drupal.org/node/2826475 has been committed, there's only [one issue](https://www.drupal.org/node/2827674) but it's not a blocker.

**Comment by drupol** [comment]
@verbruggenalex : as you're involved in menu_token, could you give us your green light for this ?

**Comment by verbruggenalex** [comment]
:+1: I was hoping the maintainer would release a beta8 cause using a commit looks a bit ugly :) But I'm fine with it. Because I was partly responsible for writing the code I would like to have a second thumbs, @tatarbj  can you have a look at this?

**Comment by Fefaine** [comment]
:+1:

**Comment by Fefaine** [comment]
I am ok with using a commit, we do that quite often, even if we prefer avoiding it, sometimes it's less ugly than using the previous versions + 20 patches :D

**Comment by netlooker** [comment]
:+1:

**Comment by netlooker** [comment]
👍

**Comment by Fefaine** [comment]
:+1:

**Pull request merged**
