### PR TITLE
NEPT-426

### PR DESCRIPTION
**Pull request by jfhovinne**
Should include missing commits/fixes due to previous merge conflicts, after fixing this PR merge conflict.

### CODE REVIEW

**Comment by drupol** [comment]
I guess these commites has already been reviewed in their own issue ?

**Comment by jfhovinne** [comment]
Yes. To cleanup the branch, I started from commit 915ef517079522ea89272097ca5843e0cb5aef6d and re-applied commits from tickets, resolved conflicts, and added latest fixes from NEPT-261-4.

**Comment by drupol** [comment]
👍

**Comment by voidtek** [comment]
:+1:

**Comment by ademarco** [comment]
👍

**Comment by netlooker** [comment]
👍

**Pull request merged**
