### PR TITLE
NEPT-250: Run unit tests at each build

### PR DESCRIPTION
**Pull request by ademarco**

### CODE REVIEW

**Comment by drupol** [comment]
Even if I don't like tests... I have to say that this is very welcome :-)

Congratulations mate!

**Comment by ademarco** [comment]
@drupol you love tests! :D

**Comment by dxvargas** [comment]
👍

**Comment by dxvargas** [comment]
👍

**Comment by ademarco** [comment]
Closing in favour of a better named branch on PR #1351

**Pull request closed without merging**
