### PR TITLE
NEPT-591: Remove contrib module 'node_export'

### PR DESCRIPTION
**Pull request by drupol**

### CODE REVIEW

**Comment by drupol** [comment]
Retriggering the tests with an updated patch.

**Comment by gillesdeudon** [comment]
:+1:

**Comment by Fefaine** [comment]
:-1:

**Comment by Fefaine** [comment]
Line 42 of UPGRADING should contain the drush command needed to remove the modules that were removed in the 2.4 release
I see it contains steps to remove modules that were already removed in 2.3

**Comment by voidtek** [comment]
@Fefaine The change is done.

**Comment by Fefaine** [comment]
:+1:

**Comment by Fefaine** [comment]
:+1:

**Comment by dxvargas** [comment]
👍

**Pull request merged**
