### PR TITLE
NEPT-717: Advanced PIWIK rules feature - QA suggestions

### PR DESCRIPTION
**Pull request by netlooker**
Follow up of the #1259 PR to implement the suggestions proposed by the QA team.

### CODE REVIEW

**Comment by Fefaine** [comment]
:+1:

**Comment by verbruggenalex** [comment]
:+1:

**Comment by Fefaine** [comment]
I asked @verbruggenalex to have a check too

**Comment by Fefaine** [comment]
:+1:

**Comment by dxvargas** [comment]
👍

**Pull request merged**
