### PR TITLE
NEXTEUROPA-11356: Adding patch for setting up default timeout for all…

### PR DESCRIPTION
**Pull request by netlooker**
Adding patch. After build no additional tasks are needed to make it work.
This is temporary solution to process with 500 errors investigation.

### CODE REVIEW

**Comment by jfhovinne** [comment]
:+1:

**Comment by jfhovinne** [comment]
Patch looks good and applies correctly. Not tested.

**Comment by voidtek** [comment]
:+1:

**Comment by voidtek** [comment]
Not tested in VPS.

**Comment by degliwe** [comment]
:+1:

**Pull request merged**
