### PR TITLE
NEPT-405: Exception messages improvements

### PR DESCRIPTION
**Pull request by aritomelo**
### Description

On multisite_config module, the exceptions messages have been improved

### Change log

- Changed:
  Exception messages

### CODE REVIEW

**Comment by jfhovinne** [comment]
Commit message should respect the agreed pattern.

**Comment by aritomelo** [comment]
@jfhovinne is it know correct? thx!

**Comment by drupol** [comment]
:+1:

**Comment by Medi4tor** [comment]
OK , but we will wait Jenkins to approve the PR and merge.

**Pull request merged**
