### PR TITLE
NEPT-2489: Update Atomium and EC Europa.

### PR DESCRIPTION
**Pull request by drupol**
## NEPT-2489

### CODE REVIEW

**Comment by aritomelo** [comment]
This PR is waiting for the Atomium release 2.x.28

**Comment by Fefaine** [comment]
@aritomelo  can you explain why you are waiting release 2.26 of atomium and point to a revision?
I see that atomium has released 2.27, so i'm a bit confused.
FYI we have to freeze 2.5.138 tomorrow. Thanks !

**Comment by drupol** [comment]
@Fefaine The comment was written more than 2 weeks ago and we released Atomium 2.27 since then.
Right now we are a bit blocked with an issue with the pager component and that's what is preventing us of releasing.

**Comment by aritomelo** [comment]
@Fefaine I am checking what is it. I will keep you posted asap.

**Review by aritomelo — APPROVED** [review]
OK!

**Comment by aritomelo** [comment]
@Fefaine The Atomium version has been released and the ticket is updated accordingly, so you can proceed in your side.

**Pull request merged**
