### PR TITLE
Hotfix/nept 423

### PR DESCRIPTION
**Pull request by jfhovinne**
Commit from origin/nept-261-5 by @drupol, within a proper ticket so it can be reviewed.
Should solve code style issues.

### CODE REVIEW

**Comment by drupol** [comment]
Just for the sake of being complete, this PR includes the PHPCS fixes + the definitions of the missing properties.
In newer version of Coder and subtools, this raise an error when those properties are not defined and when it goes through unset() instead of array reinitialization.

**Comment by Fefaine** [comment]
👍

**Comment by netlooker** [comment]
👍

**Comment by voidtek** [comment]
:+1:

**Pull request merged**
