### PR TITLE
chore(configuration): make screenshots on failing tests

### PR DESCRIPTION
**Pull request by cyberwolf**
Implements NEPT-166.

### CODE REVIEW

**Comment by ademarco** [comment]
Testing. This looks great as we can have screenshot of failing tests on CPHP available online for a limited period of time thanks to `bex/behat-screenshot-image-driver-uploadpie`!

**Comment by ademarco** [comment]
Looks good! It correctly took a screenshot for my failing step for scenario tagged as `@javascript`

**Comment by ademarco** [comment]
👍

**Comment by tatarbj** [comment]
:+1:

**Pull request merged**
