### PR TITLE
NEPT-2151: Upgrade the newsroom version, as requested by NEMA team.

### PR DESCRIPTION
**Pull request by Fefaine**
### Description

Upgrade the newsroom version, as requested by NEMA team.

### Change log

- Changed: Newsroom version changed from 3.5.2 to 3.5.5

### Commands

[Insert commands here]

### CODE REVIEW

**Review by aritomelo — DISMISSED** [review]
Just double check if there is hook_update, no update, should go here at version 2.5.
Build platform OK.

**Review by ku-enza — DISMISSED** [review]

**Review by drupol — CHANGES_REQUESTED** [review]
Commit log message "iNEPT" instead of "NEPT"

**Review by drupol — DISMISSED** [review]

**Comment by drupol** [comment]
Excellent :-)

**Review by drupol — APPROVED** [review]
:+1:

**Review by ku-enza — APPROVED** [review]
Ok

**Pull request merged**
