### PR TITLE
NEXTEUROPA-11012: add missing properties to documents sent to the backend

### PR DESCRIPTION
**Pull request by jfhovinne**
Add canonical urls and update document type field.

### CODE REVIEW

**Comment by yhuard** [comment]
👍

**Comment by ademarco** [comment]
👍 👍

**Comment by yhuard** [comment]
👍

**Comment by tatarbj** [comment]
:-1: $wrapper doesn't need to be loaded if the execution is not in 'node' case, it should be there for having less performance issues.

**Comment by tatarbj** [comment]
my vote doesn't count :'(

**Comment by yhuard** [comment]
@tatarbj one comment with your vote and one for your message I guess

**Comment by tatarbj** [comment]
:-1:

**Comment by tatarbj** [comment]
woohoo, thanks @yhuard my veto is there :dancer:

**Comment by ademarco** [comment]
@tatarbj I'll move those two lines in the `case` statement.

**Comment by ademarco** [comment]
@tatarbj @yhuard @jfhovinne done, how does that look now?

**Comment by tatarbj** [comment]
:+1:

**Comment by yhuard** [comment]
👍

**Pull request merged**
