### PR TITLE
NEXTEUROPA-11864: Fix LDAP user import

### PR DESCRIPTION
**Pull request by cyberwolf**

### CODE REVIEW

**Comment by cyberwolf** [comment]
Manually restarted the build: https://continuousphp.com/git-hub/ec-europa/platform-dev/build/30f2425e-00f7-465c-83a0-a31f9676130c/output

**Comment by voidtek** [comment]
:+1:

**Comment by jfhovinne** [comment]
:+1: 
Code looks good, not tested though.

**Comment by jfhovinne** [comment]
:+1:

**Pull request merged**
