### PR TITLE
feature(interoperability): add web frontend cache purge rules

### PR DESCRIPTION
**Pull request by cyberwolf**

### CODE REVIEW

**Comment by voidtek** [comment]
:+1:

**Comment by netlooker** [comment]
👍

**Comment by tatarbj** [comment]
@cyberwolf could you contact with Gregory, last time when we saw curl implementation by a subsite he said they should use drupal_http_request because it is handled by ec proxy things, he knows it better but maybe if it will be deployed it won't fully work because of curl.

**Comment by cyberwolf** [comment]
Don't worry, it is based on existing code. I tested it on playground and it works as expected.

**Pull request merged**
