### PR TITLE
NEPT-755: Remove the hard config that force authenticated users to be able to comment

### PR DESCRIPTION
**Pull request by AlbaParrilla**
### Description

Remove the hard config that force authenticated users to be able to comment. To do so the variables comment_xx (xx = content type) have been removed from info and strongarm files of all the features containing content types. The function setDefaultCommentForContentType() has been used in hook_install order to set the variable in each feature.

### Change log

- Added: call to the function setDefaultCommentForContentType() in .install files
- Removed: comment_xx variables from .info and from .strongarm.inc

### CODE REVIEW

**Review by ku-enza — APPROVED** [review]
I approve this.

**Review by Fefaine — APPROVED** [review]
Approving on behalf of ENrique

**Review by Fefaine — CHANGES_REQUESTED** [review]
disapproving on my behalf :)
See ticket for comments

**Comment by Fefaine** [comment]
replaced with https://github.com/ec-europa/platform-dev/pull/2351

**Pull request closed without merging**
