### PR TITLE
feat(interoperability): allow web frontend cache purge request alteration functions to change the request

### PR DESCRIPTION
**Pull request by cyberwolf**
Implements NEXTEUROPA-11479.

### CODE REVIEW

**Comment by drupol** [comment]
Hi,

I reviewed the module. I never used Varnish but I can undersrtand the logic behing it.
I have a simple question: Why don't you use a new hook instead of

`if (function_exists('fp_alter_request_for_cache_page')) {`

Thanks.

**Comment by drupol** [comment]
Never mind, this is because the module **flexible_purge** works that way.

**Comment by drupol** [comment]
:+1:

**Comment by netlooker** [comment]
👍

**Pull request merged**
