### PR TITLE
NEPT-1314:Update module to 1.2 

### PR DESCRIPTION
**Pull request by enriquelacoma**
### Description

Update module apachesolr_multisitesearch 

### Change log

- Changed: Change apachesolr_multisitesearch  version to 1.2 on apachesolr_multisitesearch

### CODE REVIEW

**Review by drishu — APPROVED** [review]

**Comment by drupol** [comment]
Typo in the commit log, missing name of the module:

`NEPT-1314: Update apachesolr_multisitesearch to version 1.2.`

**Comment by drupol** [comment]
To fix this:

1. git commit --amend
2. (update the commit log)
3. git push origin --force-with-lease

**Review by drupol — CHANGES_REQUESTED** [review]
Please update the commit log.

**Review by drishu — DISMISSED** [review]

**Review by AlbaParrilla — APPROVED** [review]
Ok for me

**Pull request merged**
