### PR TITLE
NEPT-2570: Add NextEuropa cookie consent kit module

### PR DESCRIPTION
**Pull request by msnassar**
### Add new custom module (NextEuropa cookie consent kit) 

New custom module which integrates the platform with the webtool Cookie Consent Kit (CCK) for both the banner and the video/iframe

### Change log

- Changed:
Move the code for the cookie consent for the video from ec_embedded_video to the new module.
Changed the tpl variable from $ec_embedded_video_url to $url for all media_provider_video theme functions.
- Deprecated:
EC_EMBEDDED_VIDEO_COOKIE_CONSENT_WEBSERVICE_PRURL (will be removed from platform:2.6)

### Commands

drush en nexteuropa_cookie_consent_kit

### CODE REVIEW

**Review by gillesdeudon — CHANGES_REQUESTED** [review]
The PR must be rebased on release-138.2 as we need just this module in the next deployment.

**Review by gillesdeudon — APPROVED** [review]
Rebase is done. I approve this but that does not prevent code reviewer to check it also.

**Review by AlbaParrilla — APPROVED** [review]
Ok for me 👍

**Review by tomv-be — APPROVED** [review]

**Review by AlbaParrilla — APPROVED** [review]
Ok for me 👍

**Review by tomv-be — APPROVED** [review]

**Pull request merged**
