### PR TITLE
NEXTEUROPA-11602 : update the module views to the version 7.x-3.14, r…

### PR DESCRIPTION
**Pull request by voidtek**
…emove a unused patch and clean patchs

https://webgate.ec.europa.eu/CITnet/jira/browse/NEXTEUROPA-11602

### CODE REVIEW

**Comment by jfhovinne** [comment]
:+1:

**Comment by voidtek** [comment]
:+1:

**Comment by degliwe** [comment]
:+1:

**Comment by dxvargas** [comment]
👍

**Comment by voidtek** [comment]
replaced with https://github.com/ec-europa/platform-dev/pull/684

**Pull request closed without merging**
