### PR TITLE
Feature/nexteuropa 11581

### PR DESCRIPTION
**Pull request by jfhovinne**
Flexible Purge and Integration rules.

### CODE REVIEW

**Comment by netlooker** [comment]
👍

**Comment by Fefaine** [comment]
:+1:

**Comment by dxvargas** [comment]
:+1:

**Comment by tatarbj** [comment]
sorry for my question but all of these rules are going to be enabled manually? because active 'properties' are false everywhere. i hope it won't depend on the webmasters but will be managed by centralised workflow, like rules ui should be disabled on the subsites.

**Comment by netlooker** [comment]
Flexible purge module is already on the production almost since the beginning.
The goal of the ticket was to deliver additional solution for Varnish cache invalidation for sites which request it. Core functionality of the flexible purge module stays untouched.
For the moment there is possibility to turn on those rules via drush on those particular sites which requested that functionality.
We are still under discussion regarding enabling all of them by default.

**Comment by degliwe** [comment]
:+1:

**Pull request merged**
