### PR TITLE
Running the full tests on travis-ci.org as well

### PR DESCRIPTION
**Pull request by gboddin**
- Added behat testing
- Added CS testing

### CODE REVIEW

**Comment by gboddin** [comment]
Updated to additionally test on : 

php 5.5 / mysql 5.5
php 5.6 / mysql 5.6
php 5.6 / mysql 5.7
php 5.6 / mariadb 10.0
php 5.6 / percona 5.6

**Comment by degliwe** [comment]
That's interesting, can we extract some figures in order to compare the performances of Travis VS CPHP ?

**Comment by gboddin** [comment]
To be honnest this is for 2 purposes :
- Get releases published on the github page ( soon supported by cphp )
- Get a point of comparaison the day something odd happens during testing

Besides that, cPhp will do a better job a spawning parrallel jobs than travis. For that precise reason, I limited travis to test only pull requests and deliver release.

Anyway, the testing time is arround 10 minutes to tests 2 versions of PHP + 3 version of MySQL on travis.

**Comment by gboddin** [comment]
Closing the pr but leaving the branch, in case someone needs it

**Pull request closed without merging**
