### PR TITLE
bugfix/NEXTEUROPA-7719

### PR DESCRIPTION
**Pull request by netlooker**
Reverting changes on the master branch to the state before EATURE/NEXTEUROPA-7719-2 - Simplify Poetry UI (#820) merge.

Reverted commits:
- a6a9d6be708909cb84d5d735b63e0f38fa595b93
- 654aaf50645f3b8a9a685e90e47d6c92da1bd699 - merge commit
- 74075adbbd1f17793807540ab9df47e4438edf9f - merge commit
- 55e0f4ece24a9257e13e20e690f5e0b9f69c41eb

### CODE REVIEW

**Comment by Fefaine** [comment]
@netlooker  The original PR had 6 files changes this one has 14 ?
https://github.com/ec-europa/platform-dev/pull/820/files

**Comment by netlooker** [comment]
This PR reverts master branch to the 2.2.115 release -> https://github.com/ec-europa/platform-dev/compare/2403812...bugfix/NEXTEUROPA-7719

**Comment by Fefaine** [comment]
:+1:

**Comment by jfhovinne** [comment]
:+1:

**Pull request merged**
