### PR TITLE
Feature/nexteuropa 11173

### PR DESCRIPTION
**Pull request by Fefaine**

### CODE REVIEW

**Comment by Fefaine** [comment]
:+1:

**Comment by netlooker** [comment]
👍  Finally I was able to set up environment for testing and debugging Behat tests. I didn't noticed any issues regarding test which is included in this PR.

**Comment by netlooker** [comment]
👍

**Comment by degliwe** [comment]
looks beautiful :+1:

**Comment by degliwe** [comment]
:+1:

**Comment by Fefaine** [comment]
:dancer:

**Pull request merged**
