### PR TITLE
NEXTEUROPA-12801 Composer: update coder version

### PR DESCRIPTION
**Pull request by dxvargas**
no additional commands needed

### CODE REVIEW

**Comment by jfhovinne** [comment]
Commit looks good.
Coder is correctly updated while buiding, and phpcs works as expected (see NEXTEUROPA-4429).
Build and install are OK.

**Comment by jfhovinne** [comment]
:+1:

**Comment by gillesdeudon** [comment]
I do meet any problem while building and installing the platform.

**Comment by gillesdeudon** [comment]
:+1:

**Comment by netlooker** [comment]
👍

**Pull request merged**
